
-- MySQL Script generated by MySQL Workbench
-- Seg 20 Nov 2017 09:18:33 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbpf01
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbpf01
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbpf01` DEFAULT CHARACTER SET utf8 ;
USE `dbpf01` ;

-- -----------------------------------------------------
-- Table `dbpf01`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpf01`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `nascimento` DATE NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpf01`.`ProcessoSeletivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpf01`.`ProcessoSeletivo` (
  `idProcessoSeletivo` INT NOT NULL,
  `tempoInicioCadastro` DATETIME NOT NULL,
  `tempoFimCadastro` DATETIME NOT NULL,
  `idAdministrador` INT NOT NULL,
  PRIMARY KEY (`idProcessoSeletivo`),
  INDEX `fk_ProcessoSeletivo_Administrador1_idx` (`idAdministrador` ASC),
  CONSTRAINT `fk_ProcessoSeletivo_Administrador1`
    FOREIGN KEY (`idAdministrador`)
    REFERENCES `dbpf01`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpf01`.`Prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpf01`.`Prova` (
  `idProva` INT NOT NULL AUTO_INCREMENT,
  `idProcessoSeletivo` INT NOT NULL,
  `tempoInicio` DATETIME NOT NULL,
  `tempoFim` DATETIME NOT NULL,
  PRIMARY KEY (`idProva`),
  INDEX `fk_Prova_ProcessoSeletivo1_idx` (`idProcessoSeletivo` ASC),
  CONSTRAINT `fk_Prova_ProcessoSeletivo1`
    FOREIGN KEY (`idProcessoSeletivo`)
    REFERENCES `dbpf01`.`ProcessoSeletivo` (`idProcessoSeletivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpf01`.`Elaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpf01`.`Elaborador` (
  `idElaborador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(80) NULL,
  `nascimento` DATE NULL,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idElaborador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpf01`.`Questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpf01`.`Questao` (
  `idQuestao` INT NOT NULL AUTO_INCREMENT,
  `dificuldade` INT NOT NULL,
  `usada` TINYINT(1) NOT NULL,
  `descricao` MEDIUMTEXT NOT NULL,
  `tema` VARCHAR(100) NOT NULL,
  `idProva` INT NULL,
  `idElaborador` INT NOT NULL,
  PRIMARY KEY (`idQuestao`),
  INDEX `fk_Questao_Prova1_idx` (`idProva` ASC),
  INDEX `fk_Questao_Elaborador1_idx` (`idElaborador` ASC),
  CONSTRAINT `fk_Questao_Prova1`
    FOREIGN KEY (`idProva`)
    REFERENCES `dbpf01`.`Prova` (`idProva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questao_Elaborador1`
    FOREIGN KEY (`idElaborador`)
    REFERENCES `dbpf01`.`Elaborador` (`idElaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpf01`.`Alternativas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpf01`.`Alternativas` (
  `idAlternativas` INT NOT NULL AUTO_INCREMENT,
  `descricao` MEDIUMTEXT NOT NULL,
  `idQuestao` INT NOT NULL,
  `alternativaCorreta` TINYINT(1) NULL,
  PRIMARY KEY (`idAlternativas`),
  INDEX `fk_Alternativas_Questao1_idx` (`idQuestao` ASC),
  CONSTRAINT `fk_Alternativas_Questao1`
    FOREIGN KEY (`idQuestao`)
    REFERENCES `dbpf01`.`Questao` (`idQuestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpf01`.`Candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpf01`.`Candidato` (
  `idCandidato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(80) NULL,
  `nascimento` DATE NULL,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idCandidato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpf01`.`Recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpf01`.`Recurso` (
  `idCandidato` INT NOT NULL,
  `idQuestao` INT NOT NULL,
  `idRecurso` INT NOT NULL,
  `idProva` INT NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `deferimento` TINYINT(1) NULL,
  `justificativa` MEDIUMTEXT NULL,
  INDEX `fk_Recurso_Prova1_idx` (`idProva` ASC),
  INDEX `fk_Recurso_Questao1_idx` (`idQuestao` ASC),
  INDEX `fk_Recurso_Candidato1_idx` (`idCandidato` ASC),
  PRIMARY KEY (`idCandidato`, `idQuestao`),
  CONSTRAINT `fk_Recurso_Prova1`
    FOREIGN KEY (`idProva`)
    REFERENCES `dbpf01`.`Prova` (`idProva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recurso_Questao1`
    FOREIGN KEY (`idQuestao`)
    REFERENCES `dbpf01`.`Questao` (`idQuestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recurso_Candidato1`
    FOREIGN KEY (`idCandidato`)
    REFERENCES `dbpf01`.`Candidato` (`idCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpf01`.`CandidatoMatriculaProva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpf01`.`CandidatoMatriculaProva` (
  `idProva` INT NOT NULL,
  `idCandidato` INT NOT NULL,
  PRIMARY KEY (`idProva`, `idCandidato`),
  INDEX `fk_Prova_has_Candidato_Candidato1_idx` (`idCandidato` ASC),
  INDEX `fk_Prova_has_Candidato_Prova1_idx` (`idProva` ASC),
  CONSTRAINT `fk_Prova_has_Candidato_Prova1`
    FOREIGN KEY (`idProva`)
    REFERENCES `dbpf01`.`Prova` (`idProva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prova_has_Candidato_Candidato1`
    FOREIGN KEY (`idCandidato`)
    REFERENCES `dbpf01`.`Candidato` (`idCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbpf01`.`Resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpf01`.`Resposta` (
  `idQuestao` INT NOT NULL,
  `idCandidato` INT NOT NULL,
  `idAlternativas` INT NOT NULL,
  PRIMARY KEY (`idQuestao`, `idCandidato`),
  INDEX `fk_Resposta_Questao1_idx` (`idQuestao` ASC),
  INDEX `fk_Resposta_Candidato1_idx` (`idCandidato` ASC),
  INDEX `fk_Resposta_Alternativas1_idx` (`idAlternativas` ASC),
  CONSTRAINT `fk_Resposta_Questao1`
    FOREIGN KEY (`idQuestao`)
    REFERENCES `dbpf01`.`Questao` (`idQuestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resposta_Candidato1`
    FOREIGN KEY (`idCandidato`)
    REFERENCES `dbpf01`.`Candidato` (`idCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resposta_Alternativas1`
    FOREIGN KEY (`idAlternativas`)
    REFERENCES `dbpf01`.`Alternativas` (`idAlternativas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
